# Change these first
owner: Faustozd # Tu usuario de GitHub
repo: Taller2GHA1 # Nombre de tu repositorio

# Sitios a monitorear
sites:
  - name: Google
    url: https://www.google.com
  - name: PUCE
    url: https://www.puce.edu.ec
  - name: Sitio de Prueba Roto
    url: https://sitio-que-no-existe.abc
  - name: Facebook
    url: https://facebook.com

status-website:
  # Comenta cname y descomenta baseUrl con el nombre de tu repo
  # cname: demo.upptime.js.org
  baseUrl: /Taller2GHA1
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Monitor de Status
  introTitle: "**Monitor de Status** - Taller 2 CI/CD"
  introMessage: Página de monitoreo de status usando GitHub Actions
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
